### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [TrueMLGPro/Wi-Fi_Info#21]
Could you please increase `versionCode` with each new release? It's still stuck on `1` which means "first release", and Android doesn't recognize newer ones as updates ("already installed"). Thanks!

**Comment by TrueMLGPro** [comment]
Thanks for reporting! I'll do

**Comment by IzzySoft** [comment]
Wow! That was fast, thanks!

PS: you might wish to take a look at [this](https://www.virustotal.com/gui/file/786b93b7769173a4aad67cb858d76a47175a532f4bdf78b052d0c739c310be3d/detection/f-786b93b7769173a4aad67cb858d76a47175a532f4bdf78b052d0c739c310be3d-1591917399). Any idea what might have triggered that? I'd consider it a false positive, but not just being the usual "PUA" (Potentially Unwanted App) by some minor engine, it looks a bit scary…

**Comment by TrueMLGPro** [comment]
Woah, a friend of mine got that too when he scanned the APK on VirusTotal. It is a false positive!

**Comment by TrueMLGPro** [comment]
There is no malicious code. I think it's because I sign the APKs with a debug key. That might cause these false positive results to happen but I am not 100% sure

**Comment by IzzySoft** [comment]
As I wrote, I too think it's a false positive. I was just wondering what might be causing it. I doubt it's the debug key (though a release APK would be very welcome by many): I've uploaded other debug-signed APKs and didn't have such results. I'm not an Android dev, but on a quick glance over your code I've no idea what could have triggered that (wild guess: the checksum of some file matches that of a bad one they have).

So just to be sure: I wasn't "putting blame", I just wanted to let you know. Thanks a lot!

**Comment by TrueMLGPro** [comment]
Thank you for letting me know about these false positive results!

**Comment by TrueMLGPro** [comment]
Feel free to report any problems related to the code or the app itself.

**Comment by IzzySoft** [comment]
If I encounter any, I will. Thanks a lot so far!

**Comment by TrueMLGPro** [comment]
@IzzySoft So I have signed an apk with my new keystore (`SHA256withRSA`) and Trustlook doesn't detect it as `Android.PUA.DebugKey now.
[Here](https://www.virustotal.com/gui/file/5df6c57d80a3f13739c29d8ab97575b3a75f6d3e0276c7ee2e42822202a23185/summary) is the scan result!

**Comment by IzzySoft** [comment]
Yay, great! So the next release will get its green shield, congrats!

**Comment by TrueMLGPro** [comment]
Exactly! 😁

**Comment by TrueMLGPro** [comment]
@IzzySoft Hello, sorry if I'm disturbing you but there's a problem with a new update. I scanned a signed apk file and got another false positive. I'm not quite sure what causes it.
Check [this](https://www.virustotal.com/gui/file/aeb4f120421617e7758fb25290921a9016d630a1ca0969466d15f3ba753fd7b7/detection) link.

**Comment by IzzySoft** [comment]
Yes, I've seen the very same with several "clean builds" from F-Droid as well. If you do a web search for the name of the alleged malware component, you will find the only reports mentioning it come from Kaspersky. Note that their scanner is also part of the "VT park", but doesn't complain in the least. So I'm pretty sure this is a false positive.

Seems like VT always has (exactly?) one engine giving a lot of false positives. Currently, that seems to be MaxSecure. I wouldn't wonder if it will meet the same fate as those before: simply getting removed after a few weeks of such behavior…

**Comment by TrueMLGPro** [comment]
Alright, thank you for responding! I'll sign the new update apk with my new keystore. I hope those false-positive cases will get solved by VT ASAP. Once again, thank you for your support!

**Comment by IzzySoft** [comment]
Did you say ***new*** keystore? You're aware that a different key means a different signature, which means updates to existing installations will be refused (and users have to uninstall first)? If that's intended, make sure to point that out in the changelog.

**Comment by TrueMLGPro** [comment]
Yeah, that's right! I don't know what to do better - to sign updates with default keystore (less signature problems) or sign updates with a new keystore (less VT detections). What would you recommend?

**Comment by IzzySoft** [comment]
Are you saying using a different signature leads to different VT reports? That's very strange (but good to know); and if it's again the very same engine (MaxSecure), to me that means I'd rather ignore that engine (you can also add a note to the VT report pointing that out, and inform VT staff of this issue so they can take action).

I've no idea what "default keystore" means to you (as I haven't set up your environment). If from the security point of view both are "equally fine", you should decide for one and stick with it. Switching around with each update is deadly and will scare away your users (who might think they got a "hacked APK").

**Comment by TrueMLGPro** [comment]
Yeah, when I sign the app with my usual keystore TrustLook on VT detects an APK as `Android.PUA.DebugKey`.
And yes, you're right. I think I'll stick with my "usual keystore". Thank you once again! 😁

**Comment by IzzySoft** [comment]
Ah, now that is a detail I did not have. Using debug keys for production builds is not recommended indeed. So you might wish to switch once (to your production key), saying so in the release notes / changelog, and then stick with that. What I meant was not constantly switching; once for a good reason is fine (though a bit inconvenient for the users); if there's a way to backup/restore settings, that would be helpful (not only for that case).

**Comment by TrueMLGPro** [comment]
Oh, I got it! So I am gonna use my release key for this and future releases. 🙂

**Comment by TrueMLGPro** [comment]
Oh, and one more thing I wanted to ask. When I install my signed apk of Wi-Fi Info, Play Protect warns me about unknown app source and developer. But when I install my "usual" apk, everything is fine.
Is it ok to sign apps and distribute them if I don't have Developer License on Google Play Store?

**Comment by IzzySoft** [comment]
> Is it ok to sign apps and distribute apps if I don't have Developer License on Google Play Store

Of course it is! Had you asked whether it's OK to obtain a Google Developer License, the answer would be different ("depends" :rofl:) It's like with the "insecure sources" (aka "unknown sources" in English). Google knows only one source, and that's itself. And it wants to encourage that view. My devices do not even have any GApps on them, so the warning would be the other way around ("Warning: this app wants something with Google, are you sure?" :laughing:)

> users will get this warning message whenever they install my app

If they have GApps installed and Play Protect enabled, possibly. Should you get such reports, just add a pointer to the app's description that this *might* happen and, no, you don't want that license from G as you don't plan to publish anything there. If I'd get such a "warning" I'd count that as a good sign :smile:

**Comment by TrueMLGPro** [comment]
Hahah, I see. Thanks!
