### ISSUE TITLE
ipv6 ends with network interface

### ISSUE THREAD

**Issue by Sertonix** [TrueMLGPro/Wi-Fi_Info#48]
- [x] I am running the latest app version
- [x] I checked to make sure that issue has not already been filled

**Describe the bug**

The value of the ipv6 ended with an additional `%wlan0` after the ipv6. I expect that `wlan0` is the name of the network interface that is used.

**To Reproduce**
1. Open app
2. Read ipv6

**Expected behavior**

The ipv6 should only be the ipv6.

**Smartphone:**
 - Device: Shift5me
 - OS: Android 8.1.0

**Comment by TrueMLGPro** [comment]
This issue has already been fixed in the upcoming update, it's gonna be out soon

**Comment by TrueMLGPro** [comment]
Thank you for reporting
