### ISSUE TITLE
App does not follow system portrait/landscape lock

### ISSUE THREAD

**Issue by adiOdi** [TrueMLGPro/Wi-Fi_Info#50]
**Please answer the following questions to yourself before submitting the issue**

- [x] I am running the latest app version
- [x] I checked to make sure that issue has not already been filled

**Description**
The app rotates to and from landscape even through the rotation setting on my phone is set to locked

**To Reproduce**
1. Turn off auto rotation systemwide
2. Enter the app
3. Rotate phone
4. App changes orientation

**Expected behavior**
The app should stay in the systemwide set orientation

**Smartphone:**
 - Device: Samsung s22
 - OS: Android 13, oneUi 5.1

**Comment by TrueMLGPro** [comment]
Hello, thank you for reporting about this. Just reproduced this myself, must be something wrong with activity flags

**Comment by TrueMLGPro** [comment]
Turns out `android:screenOrientation="fullSensor"` ignores the orientation lock setting. I'll make a fix asap
