### ISSUE TITLE
SSID/BSSID is not displayed

### ISSUE THREAD

**Issue by marvellz** [TrueMLGPro/Wi-Fi_Info#57]
- [x] I am running the latest app version (Ver. app: 1.6.1)
- [x] I checked to make sure that issue has not already been filled

**Describe the bug**
SSID/BSSID is not displayed. When open app, and in notification bar.

**To Reproduce**
Run the app, look at the block SSID, BSSID, etc.

![Screenshot_2024-02-12-14-03-52-95_5d897e4cf3d577cf437814fd3fca198f](https://github.com/TrueMLGPro/Wi-Fi_Info/assets/48913829/52c6ed36-3772-4b39-9c87-938148ddf0be)
![Screenshot_2024-02-12-14-05-19-12_29b563cd0bc4fd07bd0c105b17b28204](https://github.com/TrueMLGPro/Wi-Fi_Info/assets/48913829/c5beb196-2841-497e-99b1-806f3ee2afd2)

I tried on two different networks (hidden and visible net).
I forgot the network and reconnected to it after installing the app, it still displays - N/A.
Tested it in two different languages, thought translation difficulties, but with different languages - N/A.

**Expected behavior**
The MAC-address and network name should be displayed.

**Smartphone:**
 - Device: 📱 Realme on RealmeUI 4.0 (this is one of the cleanest firmware)
 - OS: Android 13, SDK 33

**Comment by TrueMLGPro** [comment]
Hello, did you enable the Location service on your device?
